# Generated by Django 5.2.7 on 2026-05-28 07:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('website', models.URLField()),
                ('description', models.TextField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField()),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('scope_type', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('vdp', 'VDP - Vulnerability Disclosure Program')], default='public', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('bounty_policy', models.TextField(blank=True)),
                ('min_bounty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_bounty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('allow_anonymous', models.BooleanField(default=False)),
                ('require_ndas', models.BooleanField(default=False)),
                ('invitation_only', models.BooleanField(default=False)),
                ('requires_application', models.BooleanField(default=False)),
                ('testing_guidelines', models.TextField(blank=True)),
                ('report_guidelines', models.TextField(blank=True)),
                ('disclosure_policy', models.TextField(blank=True)),
                ('total_reports', models.IntegerField(default=0)),
                ('total_bounties', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('avg_severity_score', models.FloatField(default=0)),
                ('avg_time_to_triage', models.FloatField(default=0)),
                ('avg_time_to_resolution', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgramApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('experience', models.TextField(blank=True)),
                ('qualifications', models.TextField(blank=True)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='programs.program')),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_applications', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgramFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='programs.program')),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_programs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgramInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('revoked', 'Revoked')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='programs.program')),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgramNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_report', 'New Report'), ('report_status_change', 'Report Status Change'), ('program_update', 'Program Update'), ('new_scope', 'New Scope Added'), ('bounty_paid', 'Bounty Paid'), ('application_update', 'Application Status Update'), ('invitation', 'New Invitation')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='programs.program')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgramStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_reports', models.IntegerField(default=0)),
                ('new_reports', models.IntegerField(default=0)),
                ('resolved_reports', models.IntegerField(default=0)),
                ('total_bounties', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('avg_bounty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('avg_time_to_triage', models.FloatField(default=0)),
                ('avg_time_to_resolution', models.FloatField(default=0)),
                ('avg_time_to_bounty', models.FloatField(default=0)),
                ('critical_count', models.IntegerField(default=0)),
                ('high_count', models.IntegerField(default=0)),
                ('medium_count', models.IntegerField(default=0)),
                ('low_count', models.IntegerField(default=0)),
                ('info_count', models.IntegerField(default=0)),
                ('active_researchers', models.IntegerField(default=0)),
                ('new_researchers', models.IntegerField(default=0)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats_snapshots', to='programs.program')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=500)),
                ('target_type', models.CharField(choices=[('web_application', 'Web Application'), ('mobile_app', 'Mobile Application'), ('api', 'API/Web Service'), ('iot', 'IoT Device'), ('network', 'Network Infrastructure'), ('hardware', 'Hardware'), ('source_code', 'Source Code'), ('social_engineering', 'Social Engineering'), ('physical_security', 'Physical Security'), ('other', 'Other')], default='web_application', max_length=50)),
                ('is_in_scope', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('bounty_multiplier', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(10.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='programs.program')),
            ],
            options={
                'ordering': ['-is_in_scope', 'target_type', 'target'],
            },
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['status', 'scope_type'], name='programs_pr_status_4b52e7_idx'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['company', 'status'], name='programs_pr_company_29f20e_idx'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['slug'], name='programs_pr_slug_103929_idx'),
        ),
        migrations.AddIndex(
            model_name='programapplication',
            index=models.Index(fields=['program', 'status'], name='programs_pr_program_e42562_idx'),
        ),
        migrations.AddIndex(
            model_name='programapplication',
            index=models.Index(fields=['researcher', 'status'], name='programs_pr_researc_6d9ef8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='programapplication',
            unique_together={('program', 'researcher')},
        ),
        migrations.AddIndex(
            model_name='programfavorite',
            index=models.Index(fields=['researcher', 'created_at'], name='programs_pr_researc_05ad9f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='programfavorite',
            unique_together={('program', 'researcher')},
        ),
        migrations.AddIndex(
            model_name='programinvitation',
            index=models.Index(fields=['program', 'status'], name='programs_pr_program_53612a_idx'),
        ),
        migrations.AddIndex(
            model_name='programinvitation',
            index=models.Index(fields=['researcher', 'status'], name='programs_pr_researc_fbe75d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='programinvitation',
            unique_together={('program', 'researcher')},
        ),
        migrations.AddIndex(
            model_name='programnotification',
            index=models.Index(fields=['user', 'read', 'created_at'], name='programs_pr_user_id_702372_idx'),
        ),
        migrations.AddIndex(
            model_name='programnotification',
            index=models.Index(fields=['program', 'created_at'], name='programs_pr_program_4cd621_idx'),
        ),
        migrations.AddIndex(
            model_name='programstats',
            index=models.Index(fields=['program', 'date'], name='programs_pr_program_ce113a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='programstats',
            unique_together={('program', 'date')},
        ),
        migrations.AddIndex(
            model_name='scope',
            index=models.Index(fields=['program', 'is_in_scope'], name='programs_sc_program_0a07a4_idx'),
        ),
    ]
