# Generated by Django 5.2.7 on 2026-10-09 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="program",
            name="programs_pr_slug_103929_idx",
        ),
        migrations.RemoveIndex(
            model_name="programstats",
            name="programs_pr_program_ce113a_idx",
        ),
    ]
