# Generated by Django 5.2.7 on 2026-03-24 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programapplication',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='programfavorite',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='programinvitation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='programapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='programnotification',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='programs.program'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['slug'], name='programs_pr_slug_103929_idx'),
        ),
    ]
