# Generated by Django 5.2.7 on 2026-05-28 07:55

import django.db.models.deletion
import reports.models_attachment
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('triaged', 'Triaged'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('duplicate', 'Duplicate'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=10)),
                ('severity_score', models.IntegerField(default=0, help_text='Numeric score for severity')),
                ('time_to_triage', models.FloatField(blank=True, help_text='Hours to triage', null=True)),
                ('time_to_resolution', models.FloatField(blank=True, help_text='Hours to resolution', null=True)),
                ('steps_to_reproduce', models.TextField(blank=True, null=True)),
                ('impact', models.TextField(blank=True, null=True)),
                ('vulnerability_type', models.CharField(blank=True, max_length=100)),
                ('affected_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bounty_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cvss_vector', models.CharField(blank=True, default='', help_text='CVSS v3.1 vector string', max_length=100)),
                ('cvss_score', models.FloatField(blank=True, help_text='CVSS v3.1 base score (0.0–10.0)', null=True)),
                ('cvss_severity', models.CharField(blank=True, default='', help_text='CVSS severity label', max_length=20)),
                ('duplicate_reason', models.TextField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to=settings.AUTH_USER_MODEL)),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='reports.bugreport')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='programs.program')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('status_change', 'Status Change'), ('comment', 'Comment'), ('assignment', 'Assignment'), ('accept', 'Accept'), ('reject', 'Reject'), ('reopen', 'Reopen'), ('mark_duplicate', 'Mark as Duplicate')], max_length=20)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('steps_to_reproduce', models.TextField(blank=True, null=True)),
                ('impact', models.TextField(blank=True, null=True)),
                ('vulnerability_type', models.CharField(blank=True, max_length=100)),
                ('affected_url', models.URLField(blank=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='reports.bugreport')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reports.bugreport')),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=reports.models_attachment.report_upload_path)),
                ('size', models.BigIntegerField()),
                ('mime', models.CharField(max_length=100)),
                ('sha256', models.CharField(max_length=64)),
                ('scan_status', models.CharField(choices=[('pending', 'Pending'), ('clean', 'Clean'), ('infected', 'Infected'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='reports.bugreport')),
            ],
            options={
                'indexes': [models.Index(fields=['report', 'scan_status'], name='reports_att_report__144871_idx')],
            },
        ),
    ]
