# Generated by Django 5.2.7 on 2026-10-09 07:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0002_perf_indexes"),
        ("reports", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="bugreport",
            index=models.Index(
                fields=["status", "-created_at"], name="rpt_status_created"
            ),
        ),
        migrations.AddIndex(
            model_name="bugreport",
            index=models.Index(fields=["program", "status"], name="rpt_program_status"),
        ),
        migrations.AddIndex(
            model_name="bugreport",
            index=models.Index(
                fields=["program", "-created_at"], name="rpt_program_created"
            ),
        ),
        migrations.AddIndex(
            model_name="bugreport",
            index=models.Index(
                fields=["reporter", "-created_at"], name="rpt_reporter_created"
            ),
        ),
        migrations.AddIndex(
            model_name="bugreport",
            index=models.Index(
                fields=["assigned_to", "status"], name="rpt_assignee_status"
            ),
        ),
        migrations.AddIndex(
            model_name="bugreport",
            index=models.Index(fields=["-created_at"], name="rpt_created"),
        ),
        migrations.AddIndex(
            model_name="bugreport",
            index=models.Index(fields=["affected_url"], name="rpt_url"),
        ),
    ]
