# Generated by Django 5.2.7 on 2026-03-16 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_bugreport_assigned_to_bugreport_verification_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugreport',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='reports.bugreport'),
        ),
        migrations.AddField(
            model_name='bugreport',
            name='duplicate_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bugreport',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('triaged', 'Triaged'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('duplicate', 'Duplicate'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=10),
        ),
    ]
