# Generated by Django 5.2.7 on 2026-03-23 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
        ('reports', '0004_bugreport_duplicate_of_bugreport_duplicate_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugreport',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='programs.program'),
        ),
    ]
