# Generated by Django 5.2.7 on 2026-03-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_bugreport_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugreport',
            name='severity_score',
            field=models.IntegerField(default=0, help_text='Numeric score for severity'),
        ),
        migrations.AddField(
            model_name='bugreport',
            name='time_to_resolution',
            field=models.FloatField(blank=True, help_text='Hours to resolution', null=True),
        ),
        migrations.AddField(
            model_name='bugreport',
            name='time_to_triage',
            field=models.FloatField(blank=True, help_text='Hours to triage', null=True),
        ),
    ]
