# Generated by Django 5.2.7 on 2026-04-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_add_bugreport_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='affected_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='impact',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='steps_to_reproduce',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='vulnerability_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('status_change', 'Status Change'), ('comment', 'Comment'), ('assignment', 'Assignment'), ('accept', 'Accept'), ('reject', 'Reject'), ('reopen', 'Reopen'), ('mark_duplicate', 'Mark as Duplicate')], max_length=20),
        ),
    ]
