# Generated by Django 5.2.7 on 2026-04-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_activitylog_affected_url_activitylog_impact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugreport',
            name='cvss_score',
            field=models.FloatField(blank=True, help_text='CVSS v3.1 base score (0.0–10.0)', null=True),
        ),
        migrations.AddField(
            model_name='bugreport',
            name='cvss_severity',
            field=models.CharField(blank=True, default='', help_text='CVSS severity label', max_length=20),
        ),
        migrations.AddField(
            model_name='bugreport',
            name='cvss_vector',
            field=models.CharField(blank=True, default='', help_text='CVSS v3.1 vector string', max_length=100),
        ),
    ]
