"""
Django settings for Backend project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

from .db_config import build_caches, build_databases

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-@j0md9c!fn2v3r^ro2qis1y_x-gl0-*q#+bpm^buop*exz@xl6')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'False') == 'True'

# Ensure SECRET_KEY is set in production
if not DEBUG and SECRET_KEY == 'django-insecure-@j0md9c!fn2v3r^ro2qis1y_x-gl0-*q#+bpm^buop*exz@xl6':
    import warnings
    warnings.warn("DJANGO_SECRET_KEY is using the insecure default — set it in production!", RuntimeWarning)

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'csp',

    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',

    'users.apps.UsersConfig',
    'reports.apps.ReportsConfig',
    'programs.apps.ProgramsConfig',
    'audit.apps.AuditConfig',
    'leaderboard.apps.LeaderboardConfig',

    'django_filters',
]

# ---------------------------------------------------------------------------
# Leaderboard scoring economy
# ---------------------------------------------------------------------------
# Points granted per accepted/resolved report, weighted by severity. Override
# either of these to rebalance without touching the leaderboard code.
LEADERBOARD_SEVERITY_POINTS = {
    "low": 1,
    "medium": 3,
    "high": 7,
    "critical": 15,
}
# Report statuses that earn points (a report flagged as a duplicate never does,
# regardless of status — enforced in leaderboard.services).
LEADERBOARD_AWARD_STATUSES = ("accepted", "resolved")

REST_FRAMEWORK = {
    # Cookie-based JWT auth is the primary mechanism. The header-based
    # JWTAuthentication is kept as a fallback so existing tests / integrations
    # that send `Authorization: Bearer <token>` keep working during migration.
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'users.jwt_cookies.JWTCookieAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser',
        'rest_framework.parsers.FormParser',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_THROTTLE_RATES': {
        # Env-overridable so local demos can log in as several roles in
        # quick succession without tripping the throttle. Secure defaults.
        'login': os.environ.get('LOGIN_THROTTLE_RATE', '3/min'),
        'register': os.environ.get('REGISTER_THROTTLE_RATE', '2/min'),
        'password_reset': '2/hour',          # Per-IP: Password reset requests
        'password_reset_email': '3/hour',    # Per-target-email: blocks inbox flooding with rotating IPs
        'password_reset_confirm': '5/hour',  # Per-IP: Password reset confirmations
        'submission': '50/hour',
        'anon': '20/min',
        'user': '60/min',
        'burst': '100/minute',
        # OAuth client login — keep tighter than regular login because each
        # callback hit is a network round-trip to the provider.
        'oauth_init': '10/min',
        'oauth_callback': '10/min',
        'token_refresh': '30/min',
        # TOTP / backup code checks for logged-in users (confirm, disable, regenerate)
        'mfa_code': '10/min',
        # Pre-login 2FA enrollment for Admin/Triager (keyed by IP)
        'mfa_enroll': '20/min',
    }
}

MIDDLEWARE = [
    'csp.middleware.CSPMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'audit.middleware.AuditLogMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    o.strip() for o in os.environ.get(
        'CORS_ALLOWED_ORIGINS', 'http://localhost:3000,http://127.0.0.1:3000'
    ).split(',') if o.strip()
]
# Cookies are httpOnly + SameSite=Strict — but we still need the browser to
# attach them on cross-origin requests (React on :3000 -> API on :8000).
CORS_ALLOW_CREDENTIALS = True
# Allow the React app to send the CSRF header with cookie-authenticated calls.
CORS_ALLOW_HEADERS = list(__import__('corsheaders.defaults', fromlist=['default_headers']).default_headers) + [
    'x-csrftoken',
]

ROOT_URLCONF = 'Backend.urls'

from datetime import timedelta

SIMPLE_JWT = {
    # Short-lived access tokens — limits the damage of a stolen access token.
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    # 7-day refresh window. Refresh tokens are single-use (rotated) and the
    # old one is blacklisted on every refresh, so the effective exposure window
    # for any single refresh token is one HTTP round-trip.
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
    # `jti` is the claim we already key UserSession off; keep the default.
    "JTI_CLAIM": "jti",
}

# =============================================================================
# JWT cookie configuration
# =============================================================================
# These cookies hold the access + refresh tokens. They are HttpOnly (invisible
# to JavaScript, defeats XSS-based token theft) and SameSite=Strict (defeats
# most CSRF, though CSRF middleware is also enforced for state-changing
# requests). Secure is gated on DJANGO_SECURE_COOKIES so dev (http://localhost)
# still works.
JWT_AUTH_COOKIE = "bb_access"            # access token cookie name
JWT_AUTH_REFRESH_COOKIE = "bb_refresh"   # refresh token cookie name
JWT_AUTH_COOKIE_HTTP_ONLY = True
JWT_AUTH_COOKIE_SECURE = os.environ.get('DJANGO_SECURE_COOKIES', 'False') == 'True'
JWT_AUTH_COOKIE_SAMESITE = "Strict"
JWT_AUTH_COOKIE_PATH = "/"
# Refresh cookie is only sent to the refresh + logout endpoints — narrows
# the attack surface even if some intermediary leaks Cookie headers.
JWT_AUTH_REFRESH_COOKIE_PATH = "/api/"
# CSRF protection is enforced on cookie-authenticated state-changing requests.
JWT_AUTH_CSRF_ENFORCED = True

# =============================================================================
# OAuth client login (GitHub / Google / GitLab)
# =============================================================================
# Read provider credentials from environment so secrets never live in the repo.
# When client_id / client_secret are empty the provider is treated as disabled
# and its endpoints return 503.
OAUTH_PROVIDERS = {
    "github": {
        "client_id": os.environ.get("OAUTH_GITHUB_CLIENT_ID", ""),
        "client_secret": os.environ.get("OAUTH_GITHUB_CLIENT_SECRET", ""),
        "scope": "read:user user:email",
    },
    "google": {
        "client_id": os.environ.get("OAUTH_GOOGLE_CLIENT_ID", ""),
        "client_secret": os.environ.get("OAUTH_GOOGLE_CLIENT_SECRET", ""),
        "scope": "openid email profile",
    },
    "gitlab": {
        "client_id": os.environ.get("OAUTH_GITLAB_CLIENT_ID", ""),
        "client_secret": os.environ.get("OAUTH_GITLAB_CLIENT_SECRET", ""),
        "scope": "read_user",
    },
}
# Where the React app lives — used to build callback URLs and to redirect
# back after a successful OAuth login.
FRONTEND_URL = os.environ.get("FRONTEND_URL", "http://localhost:3000")
# Backend public origin (used to construct the redirect_uri the provider
# echoes back to). Defaults to the dev value.
BACKEND_PUBLIC_URL = os.environ.get("BACKEND_PUBLIC_URL", "http://localhost:8000")

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = build_databases(os.environ)

# Shared Redis cache when REDIS_URL is set (throttles, leaderboard); else locmem.
CACHES = build_caches(os.environ)

# ---------------------------------------------------------------------------
# Celery (background tasks)
# ---------------------------------------------------------------------------
# Broker: CELERY_BROKER_URL, else REDIS_URL. With no broker at all, tasks run
# inline (EAGER) so local dev and the test-suite need no extra services.
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL') or os.environ.get('REDIS_URL') or ''
CELERY_TASK_ALWAYS_EAGER = os.environ.get('CELERY_TASK_ALWAYS_EAGER', '') == 'True' or not CELERY_BROKER_URL
CELERY_TASK_EAGER_PROPAGATES = True
CELERY_RESULT_BACKEND = None          # fire-and-forget tasks; nothing reads results
CELERY_TASK_ACKS_LATE = True          # re-deliver if a worker dies mid-task (tasks are idempotent)
CELERY_TASK_TIME_LIMIT = 300
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_TIMEZONE = 'UTC'
CELERY_BEAT_SCHEDULE = {
    'purge-audit-logs-daily': {
        'task': 'audit.tasks.purge_audit_logs',
        'schedule': 24 * 60 * 60,
    },
}

# Security audit log rows older than this are removed by `manage.py purge_audit_logs`
# (scheduled daily by Celery beat). 0 = keep forever.
AUDIT_LOG_RETENTION_DAYS = int(os.environ.get('AUDIT_LOG_RETENTION_DAYS', '365'))



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

#Password Hashing
PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.Argon2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
]


# =============================================================================
# Security Headers
# =============================================================================
# Enable in production by setting environment variable
SECURE_SSL_REDIRECT = os.environ.get('DJANGO_SECURE_SSL', 'False') == 'True'
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Cookie Security
SESSION_COOKIE_SECURE = os.environ.get('DJANGO_SECURE_COOKIES', 'False') == 'True'
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'

# CSRF cookie — readable by JS so the React app can put the value in the
# X-CSRFToken header. The token is *bound to a session* and useless without it.
CSRF_COOKIE_SECURE = os.environ.get('DJANGO_SECURE_COOKIES', 'False') == 'True'
CSRF_COOKIE_HTTPONLY = False    # must be False so JS can read it
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in os.environ.get(
        'CSRF_TRUSTED_ORIGINS', 'http://localhost:3000,http://127.0.0.1:3000'
    ).split(',') if o.strip()
]
# Header the React app must send with state-changing requests when using
# cookie-based auth. Default Django name; spelled out for clarity.
CSRF_HEADER_NAME = 'HTTP_X_CSRFTOKEN'

# XSS Protection
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# HSTS (only in production)
if os.environ.get('DJANGO_HSTS', 'False') == 'True':
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# Trusted proxy configuration for X-Forwarded-For validation (django-ipware).
# Set to the number of reverse proxies in front of Django in production.
# 0 = direct connection (development), 1 = single nginx proxy, 2 = nginx + LB, etc.
# Never set this higher than the actual number of trusted proxies you control.
IPWARE_TRUSTED_PROXY_COUNT = int(os.environ.get('IPWARE_TRUSTED_PROXY_COUNT', '0'))

# Content Security Policy (django-csp 4.x API)
# Content Security Policy (django-csp 4.x)

CONTENT_SECURITY_POLICY = {
    "DIRECTIVES": {
        "default-src": ["'self'"],

        "script-src": ["'self'", "'nonce-{nonce}'"],
        "style-src": ["'self'", "'nonce-{nonce}'"],

        "img-src": ["'self'", "data:", "blob:"],
        "font-src": ["'self'"],
        "connect-src": ["'self'"],
        "media-src": ["'self'"],

        "frame-src": ["'none'"],
        "frame-ancestors": ["'none'"],
    },
}

# Promote to report-only mode during rollout by setting CSP_REPORT_ONLY=True in env.
if os.environ.get("CSP_REPORT_ONLY", "False") == "True":
    CONTENT_SECURITY_POLICY_REPORT_ONLY = CONTENT_SECURITY_POLICY
    CONTENT_SECURITY_POLICY = {}

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Superuser:
# username: admin
# email: admin@something.com
# password: ]LLpXFxJrR=0Of#Y

# Testuser:
# name: test
# password: test123
# name: test1
# email: test1@something.com
# password: password123

# Researcher:
# name: researcher
# email: researcher@example.com
# password: pw123456



# === File upload safety ===
MEDIA_ROOT = BASE_DIR / "media"               # stays outside any static root
MEDIA_URL = "/media/"                         # we will NOT serve MEDIA_URL publicly in prod

# 10 MB per file
MAX_UPLOAD_SIZE = 10 * 1024 * 1024

# allowlist by extension + MIME
ALLOWED_FILE_EXTENSIONS = {".png", ".jpg", ".jpeg", ".pdf", ".txt", ".zip"}
ALLOWED_MIME_TYPES = {
    "image/png", "image/jpeg", "application/pdf",
    "text/plain", "application/zip",
}

# security headers for downloads
SECURE_DOWNLOAD_CONTENT_DISPOSITION = 'attachment'

#reCAPTCHA
RECAPTCHA_SECRET_KEY = os.environ.get("RECAPTCHA_SECRET_KEY", "")
RECAPTCHA_VERIFY_URL = "https://www.google.com/recaptcha/api/siteverify"

# Email backend — use SMTP in production, console in development
_email_backend = os.environ.get('EMAIL_BACKEND', 'console')
if _email_backend == 'smtp':
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.environ.get('EMAIL_HOST', 'localhost')
    EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
    EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
    EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
    EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
elif _email_backend == 'locmem':
    EMAIL_BACKEND = 'django.core.mail.backends.locmem.EmailBackend'
else:
    # Default: console (dev)
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'no-reply@bugbounty.local')