# Generated by Django 5.2.7 on 2026-10-09 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wallet", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=60, unique=True)),
                ("name", models.CharField(max_length=80)),
                ("description", models.CharField(blank=True, max_length=300)),
                (
                    "slot",
                    models.CharField(
                        choices=[
                            ("hat", "Hat"),
                            ("face", "Face"),
                            ("body", "Body"),
                            ("pet", "Pet"),
                            ("background", "Background"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "rarity",
                    models.CharField(
                        choices=[
                            ("common", "Common"),
                            ("rare", "Rare"),
                            ("epic", "Epic"),
                            ("legendary", "Legendary"),
                        ],
                        default="common",
                        max_length=10,
                    ),
                ),
                ("price", models.PositiveIntegerField(default=0)),
                ("min_level", models.PositiveSmallIntegerField(default=1)),
                ("art", models.CharField(blank=True, default="", max_length=16)),
                ("image_url", models.URLField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["sort_order", "price", "id"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "slot"], name="store_item_active_slot"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UserItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("purchased_at", models.DateTimeField(auto_now_add=True)),
                ("price_paid", models.PositiveIntegerField(default=0)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owners",
                        to="store.item",
                    ),
                ),
                (
                    "transaction",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wallet.wallettransaction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-purchased_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="EquippedItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slot",
                    models.CharField(
                        choices=[
                            ("hat", "Hat"),
                            ("face", "Face"),
                            ("body", "Body"),
                            ("pet", "Pet"),
                            ("background", "Background"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipped",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipped",
                        to="store.useritem",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="useritem",
            constraint=models.UniqueConstraint(
                fields=("user", "item"), name="store_own_item_once"
            ),
        ),
        migrations.AddConstraint(
            model_name="equippeditem",
            constraint=models.UniqueConstraint(
                fields=("user", "slot"), name="store_one_item_per_slot"
            ),
        ),
    ]
