# Generated by Django 5.2.7 on 2026-06-08 22:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0003_company'),
        ('reports', '0009_bugreport_cvss_score_bugreport_cvss_severity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0)),
                ('severity', models.CharField(blank=True, default='', max_length=10)),
                ('awarded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='score_events', to='programs.program')),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score_event', to='reports.bugreport')),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-awarded_at'],
                'indexes': [models.Index(fields=['researcher', 'awarded_at'], name='leaderboard_researc_e6dd0b_idx'), models.Index(fields=['program', 'awarded_at'], name='leaderboard_program_ecf209_idx')],
            },
        ),
    ]
