# Generated by Django 5.2.7 on 2026-03-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('User', 'User'), ('ProgramOwner', 'Program Owner'), ('Admin', 'Admin')], default='User', max_length=20),
        ),
    ]
