# Generated by Django 5.2.7 on 2026-04-14 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('login_failed', 'Login Failed'), ('register', 'Register'), ('password_change', 'Password Change'), ('password_reset_request', 'Password Reset Request'), ('password_reset_complete', 'Password Reset Complete'), ('email_verified', 'Email Verified'), ('report_created', 'Report Created'), ('report_updated', 'Report Updated'), ('report_status_changed', 'Report Status Changed'), ('report_marked_duplicate', 'Report Marked Duplicate'), ('attachment_uploaded', 'Attachment Uploaded'), ('attachment_downloaded', 'Attachment Downloaded'), ('program_created', 'Program Created'), ('program_updated', 'Program Updated'), ('company_profile_created', 'Company Profile Created'), ('suspicious_activity', 'Suspicious Activity'), ('permission_denied', 'Permission Denied'), ('admin_access', 'Admin Access')], max_length=50)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('success', models.BooleanField(default=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('resource_id', models.CharField(blank=True, help_text='ID of affected resource', max_length=100)),
                ('resource_type', models.CharField(blank=True, help_text='Type of affected resource', max_length=50)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Security Audit Log',
                'verbose_name_plural': 'Security Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['action', '-timestamp'], name='audit_secur_action_001632_idx'), models.Index(fields=['user', '-timestamp'], name='audit_secur_user_id_83db35_idx'), models.Index(fields=['ip_address', '-timestamp'], name='audit_secur_ip_addr_ebd404_idx'), models.Index(fields=['severity', '-timestamp'], name='audit_secur_severit_cb44a9_idx')],
            },
        ),
    ]
